/* Generated by Cython 0.29.30 */

#ifndef __PYX_HAVE__yoda__core
#define __PYX_HAVE__yoda__core

#include "Python.h"

#ifndef __PYX_HAVE_API__yoda__core

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *YodaExc_Exception;
__PYX_EXTERN_C PyObject *YodaExc_BinningError;
__PYX_EXTERN_C PyObject *YodaExc_RangeError;
__PYX_EXTERN_C PyObject *YodaExc_LockError;
__PYX_EXTERN_C PyObject *YodaExc_GridError;
__PYX_EXTERN_C PyObject *YodaExc_LogicError;
__PYX_EXTERN_C PyObject *YodaExc_LowStatsError;
__PYX_EXTERN_C PyObject *YodaExc_WeightError;
__PYX_EXTERN_C PyObject *YodaExc_AnnotationError;
__PYX_EXTERN_C PyObject *YodaExc_ReadError;
__PYX_EXTERN_C PyObject *YodaExc_UserError;

#endif /* !__PYX_HAVE_API__yoda__core */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcore(void);
#else
PyMODINIT_FUNC PyInit_core(void);
#endif

#endif /* !__PYX_HAVE__yoda__core */
