# contrib-wide Makefile include file, generated automatically with
# ./configure --fastjet-config=/Users/jessicaturner/Documents/GitHub/ulysses/ulysses/local/bin/fastjet-config CXXFLAGS=-fPIC
CXXFLAGS=-fPIC
FASTJETCONFIG=/Users/jessicaturner/Documents/GitHub/ulysses/ulysses/local/bin/fastjet-config
PREFIX=/Users/jessicaturner/Documents/GitHub/ulysses/ulysses/local
install_script = $(SHELL) ../utils/install-sh
check_script = ../utils/check.sh
CXXFLAGS+=-std=c++11
